#!/usr/bin/env bash
# demo script for transfer of file to a server

if [ $# -l4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# assign arguments to variables

path_to_file = $1
ip_address = $2
username = $3
path_to_private_key = $4

#  host key checking disabled

scp -o "StrictHostKeyChecking=no" -i "$path_to_private_key" "$path_to_file" "$username@$ip_address:~/"
