#!/usr/bin/env bash
# demo script for transfer of file to a server

if [ "$#" -lt 4 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# assign arguments to variables

my_file="$1"
ip_address="$2"
username="$3"
path_to_send_file="$4"

#  host key checking disabled

scp -o StrictHostKeyChecking=no -i "$my_file" "$ip_address" "$username"@"$path_to_send_file":~/
