#!/usr/bin/env bash
# installation of Nginx on server wich custom message from root

sudo apt-get update

sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx start
