#!/usr/bin/env bash
# installing nginx to my server and applying custom root file message

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
