#!/usr/bin/env bash
# installation of Nginx on server wich custom message from root

sudo apt-get update

sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i "/rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx start
