#!/usr/bin/env bash
# installing nginx to my server and applying custom root file message
# demo of adding permanent redirection

# update packages
sudo apt-get update

#install nginx
sudo apt-get -y install nginx

# edit response header
echo "Hello World!" | sudo tee /var/www/html/index.html

redirection="server_name _;\/n\/trewrite ^https:\/\/youtube.com\/@kalichipictures8299 permanent;"

sudo sed -i "s/server_name _;/$redirection/" /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart
