#!/usr/bin/env bash
# configure new server, with custom http response header

# update packages
sudo apt-get update

# install nginx, use y flag for yes to all options
sudo apt-get install -y nginx

# custom home page message
echo "Hello World!" | sudo tee /var/www/html/index.html

# carry out a redirection
new_direction="server_name _;\n\trewrite ^\/redirect https:\/\/github.com\/kchinyama permanent;"


sudo sed -i "s/server_name _;/$new_direction/" /etc/nginx/sites-enabled/default

# create our own custom error message
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# custom response header revealing server at work
sudo sed -i "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default;

# test for errors
sudo nginx -t

# restart the server
sudo service nginx restart
