#!/usr/bin/env bash
# simple script that displays numbers from 1 - 100 with fizz and buzz displays mixed in

k=1

while [ $k -le 100 ]
do
	if (( k % 3 == 0 )) && (( k % 5 == 0 ))
	then
		echo "FizzBuzz"
	
	elif (( k % 3 == 0 ))
	then
		echo "Fizz"
	
	elif (( k % 5 == 0 ))
	then
		echo "Buzz"
	
	else
		echo $k
	fi
	k=$((k+1))
done
