#!/usr/bin/env bash
#demo script display of the imfamous fizzbuzz

for k in {1..100}
do
	if [ $((k % 15)) -eq 0 ]
	then
		echo "FizzBuzz"

	elif [ $((k % 5)) -eq 0 ]
	then
		echo "Buzz"

	elif [ $((k % 3)) -eq 0 ]
	then
		echo "Fizz"

	else
		echo "$k"
	fi
done
