#!/usr/bin/env bash
# simple shell script that displays "Best School" and "Hi" on a new line
#+ with the use of a while loop and if statement

k=0

while (( k<10 ))
do
	echo "Best School"

	if ((k == 8))
	then
		echo "Hi"
	fi
k=$((k+1))
done
