#!/usr/bin/env bash
# simple script demonstrating the use of while loop, if, elif and else statement
#+ to print messages

k=0

while ((k<10))
do
	if ((k == 3))
	then
		echo "bad luck"

	elif ((k == 7))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	k=$((k+1))
done
