#!/usr/bin/env bash
#demo script that prints Best School, bad luck and good luck

k=0

while [ $k -lt 9 ]
do
if [ $k -eq 3 ]
then
echo "bad luck"
elif [ $k -eq 7 ]
then
echo "good luck"
else
echo "Best School"
fi
((k++))
done

