#!/usr/bin/env bash
# script that displays numbers 1 - 20 with custom strings at certain iterations using while loop 
#+ and case statement

k=1

while (( k <= 20 ))
do
case $k in
5)
	echo "bad luck from China";;
10)
	echo "bad luck from Japan";;
18)
	echo "bad luck from Italy";;
*)
esac
	echo $k
	k=$((k+1))
done
