#!/usr/bin/env bash
#demo script displaying use of while and case statement to iterate

nums=1

while [ $nums -lt 21 ]
do
echo $nums
case $nums in 4)
echo "bad luck from China";;
9)
echo "bad luck from Japan";;
17)
echo "bad luck from Italy";;
*);;
esac
((nums++))
done
