#!/usr/bin/env bash
# simple bash script that displays time for 12 hours and 59 minutes:
#+ displays hours from 0 to 12
#+ display minutes from 1 to 59

k=0 # count for hours

while (($k <= 12))
do
	echo "Hour: $k"
	n=1 # count for minutes
	while (($n < 60 ))
	do
		echo $n
		n=$((n+1))
	done
	k=$((k+1))
done
